### ISSUE TITLE
Settings windows uses @font-family-code

### ISSUE THREAD

**Issue by dsandstrom** [emilyemorehouse/spacegray-monokai-ui#1]
I'm not sure if it was your intention, but the Settings windows uses the "code" font.  I narrowed it down to line 17 in panes.less.  Other ui themes that I have looked at don't have a font rule for `.panes .pane`.  Looks good otherwise, thanks.

Edit. I should clarify.  I noticed your other spacegray themes have the same issue.  Other ui themes, like atom-dark-ui, dont declare a font.

**Comment by AndreasBackx** [comment]
In case you still need this @dsandstrom [here](https://github.com/AndreasBackx/spacegray-monokai-ui) is a working fork. [I made a pull request.](https://github.com/emilyemorehouse/spacegray-monokai-ui/pull/2)
